#!/bin/bash
if (( $# == 0 )); then
    echo "Showing some help:"
    echo ""
    echo "The following rules apply when a scripting language is found:"
    echo " * \$1 is the file you want to (DELETE and) create and \`chmod +x\`"
    echo "   It will be then opened in \$EDITOR (current value is: '$EDITOR')"
    echo " * \$2 is an optinal reference. Put it if you want the file to be shbanged as '#!/usr/bin/\$2'"
    echo "The following rules apply when a programming language is found:"
    echo " * \$1 should be the file name, a basic structure will be made if it does not exist."
    echo "   If \$1 exists, it will be compiled"
    exit 1
fi
if [ ! -e "$1" ]; then
    if (( $# == 1 )); then
	_pp='bash'
	if   [ 1 -eq "$(echo "$1" | egrep -c ".*\.awk")" ]; then
	    _pp='awk -f'
	elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.p(l|m)")" ]; then
	    _pp='perl'
	elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.p6(m)?")" ]; then
	    _pp='perl6'
	elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.py")" ]; then
	    _pp='env python'
	elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.zsh")" ]; then
	    _pp='zsh'
	elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.java")" ]; then
	    echo "public class $(echo "$1" | perl -pe 's/(.*?\/)*(.*?)\.java/$2/') {" > $1
	    echo "    " >> $1
	    echo "}"    >> $1
	    $EDITOR $1
	    exit 0
	elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.h(pp)?")" ]; then
	    name="$(echo "$1" | perl -pe 's/(.*?\/)*(.*?)\.h(pp)?/$2/' | perl -pe 's/([a-z])([A-Z])/$1_$2/g' | tr '[a-z]' '[A-Z]' | tr - _)"
	    echo "#ifndef ${name}_H" >  $1
	    echo "#define ${name}_H" >> $1
	    echo ""                  >> $1
	    echo "#endif"            >> $1
	    $EDITOR $1
	    exit 0
	elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.(c|cpp|ml|mli)")" ]; then
	    $EDITOR $1
	    exit 0
	    
	    #Base:
	    #elif [ 1 -eq $(echo "$1" | egrep -c ".*\.") ]; then
	    #	_pp=''
	fi
	echo "#!/bin/$_pp" > $1
    else
	echo "#!/bin/$2" > $1
    fi
    chmod +x $1
    $EDITOR $1
else
    if   [ 1 -eq "$(echo "$1" | egrep -c ".*\.h(pp)?")" ]; then echo "Don't know how to compile header files"
    elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.c")" ];      then gcc -c $1
    elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.cpp")" ];    then g++ -c $1
    elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.hs")" ];     then ghc -c $1
    elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.java")" ];   then javac $1
    elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.ml")" ];     then
	echo "ml files are assumed to be OCaml files (compile after .mli files)"
	ocamlopt -c $1
    elif [ 1 -eq "$(echo "$1" | egrep -c ".*\.mli")" ];    then
	echo "ml files are assumed to be OCaml files (compile before .ml files)"
	ocamlc -c $1
    else
	chmod +x $1
	./$1
    fi
fi
